CREATE TABLE IF NOT EXISTS user_mocks
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    description      TEXT,
    priority         INT          NOT NULL DEFAULT 100,
    source           VARCHAR(50)  NOT NULL DEFAULT 'manual',
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL
);

ALTER TABLE user_mocks ADD COLUMN IF NOT EXISTS priority INT NOT NULL DEFAULT 100;
ALTER TABLE user_mocks ADD COLUMN IF NOT EXISTS source VARCHAR(50) NOT NULL DEFAULT 'manual';

